Repository shdq/spartak-ui, pull requests merged in 2023-05, with the labels that each got.

#66 chore(ci): update `publish to npm` workflow to add provenance (digital signature)
  .github/workflows/publish-to-npm.yml
Labels: maintenance, CI

#67 docs(examples): switch to storybook theme toggle button for UI examples
  components/examples/Spotify/App.tsx
  components/examples/Twitter/App.tsx
  components/examples/YouTube/App.tsx
  components/examples/stories/Spotify.stories.tsx
  components/examples/stories/Twitter.stories.tsx
  components/examples/stories/YouTube.stories.tsx
Labels: documentation

#68 fix(text): fix bug with regular font-weight when `Text` component renders as `strong` or `b` element
  components/text/Text.tsx
Labels: bug, group: Typography, component: Text

#69 docs(readme): add installation instructions for `npm` and `yarn`
  README.md
Labels: documentation

#44 feat(checkbox): add `Checkbox` component
  components/card/stories/Card.stories.tsx
  components/checkbox/Checkbox.test.tsx
  components/checkbox/Checkbox.tsx
  components/checkbox/README.md
  components/checkbox/index.ts
  components/checkbox/stories/Checkbox.stories.tsx
  components/index.ts
  components/stitches.config.ts
  components/text-input/README.md
  components/text-input/TextInput.test.tsx
  components/text-input/TextInput.tsx
  components/text-input/stories/TextInput.stories.tsx
Labels: enhancement, component: Checkbox, group: Forms

#71 chore(release): bump vestion, update deps
  package-lock.json
  package.json
Labels: maintenance
